# Generated by Django 3.1.7 on 2021-04-18 11:34

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Текст вопроса')),
                ('correct', models.BooleanField(verbose_name='Ответ верен?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionapp.question', verbose_name='относится к вопросу')),
            ],
        ),
    ]
