# Generated by Django 3.1.7 on 2021-05-06 07:22

from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0017_comment'),
        ('questionapp', '0003_question_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=512, verbose_name='Текст карточки')),
                ('image', easy_thumbnails.fields.ThumbnailerImageField(blank=True, null=True, upload_to='card_img/', verbose_name='Картинка карточки')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainapp.topic', verbose_name='Тема теста')),
            ],
        ),
    ]
