# Generated by Django 3.1.7 on 2021-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Картинка карточки')),
                ('header', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('text', models.CharField(max_length=512, verbose_name='Текст карточки')),
            ],
        ),
    ]
