# Generated by Django 3.1.7 on 2021-03-16 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='header',
            new_name='title',
        ),
    ]
