# Generated by Django 3.1.7 on 2021-03-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20210316_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(height_field=400, upload_to='card_img/', verbose_name='Картинка карточки', width_field=250),
        ),
    ]
