# Generated by Django 3.1.7 on 2021-03-23 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_content_card'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Content_Card',
            new_name='ContentCard',
        ),
    ]
