# Generated by Django 3.1.7 on 2021-03-23 08:34

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_auto_20210323_0722'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcard',
            name='label',
            field=models.CharField(blank=True, max_length=16, verbose_name='обозначение карты'),
        ),
        migrations.AlterField(
            model_name='contentcard',
            name='text',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Содержание карточки'),
        ),
    ]
