# Generated by Django 3.1.7 on 2021-03-25 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_auto_20210323_0834'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=16, verbose_name='Тема')),
            ],
        ),
        migrations.RemoveField(
            model_name='contentcard',
            name='label',
        ),
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=1000, verbose_name='Порядковый номер карточки'),
        ),
        migrations.AddField(
            model_name='card',
            name='topic_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.topic'),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='topic_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='mainapp.topic'),
        ),
    ]
