# Generated by Django 3.1.7 on 2021-03-25 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0010_remove_card_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentcard',
            name='topic_id',
        ),
    ]
