# Generated by Django 3.1.7 on 2021-03-25 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0011_remove_contentcard_topic_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='order',
            field=models.IntegerField(default=1000, verbose_name='Порядковый номер карточки'),
        ),
        migrations.AddField(
            model_name='card',
            name='topic_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to='mainapp.topic'),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='topic_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='mainapp.topic'),
        ),
    ]
