# Generated by Django 3.1.7 on 2021-03-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0014_auto_20210325_0808'),
    ]

    operations = [
        migrations.AddField(
            model_name='contentcard',
            name='label',
            field=models.CharField(default=models.IntegerField(default=1000, verbose_name='Порядковый номер карточки'), max_length=32, verbose_name='Обозначение карточки при пагинации'),
        ),
        migrations.AddField(
            model_name='contentcard',
            name='order',
            field=models.IntegerField(default=1000, verbose_name='Порядковый номер карточки'),
        ),
    ]
